# Generated by Django 3.2.6 on 2021-08-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
