# Generated by Django 3.2.6 on 2021-08-20 06:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210820_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='select_country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='your_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
