# Generated by Django 3.2.6 on 2021-08-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_select_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='your_name',
            new_name='full_name',
        ),
    ]
