# Generated by Django 3.2.6 on 2021-08-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_change_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='change_avatar',
        ),
    ]
