# Generated by Django 3.2.6 on 2021-08-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210825_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_font', models.CharField(blank=True, choices=[('select_font', 'Select Font'), ('tajawai', 'Tajawai')], max_length=255, null=True)),
            ],
        ),
    ]
