# Generated by Django 3.2.6 on 2021-09-01 03:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_fonts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonts',
            name='site_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='fonts',
            name='site_font',
            field=models.CharField(blank=True, choices=[('select_font', 'Select Font'), ('tajawal', 'Tajawai')], max_length=255, null=True),
        ),
    ]
