# Generated by Django 3.2.6 on 2021-09-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20210901_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonts',
            name='site_font',
            field=models.CharField(blank=True, choices=[('select_font', 'Select Font'), ('tajawal', 'Tajawai')], default=1, max_length=255, null=True),
        ),
    ]
