# Generated by Django 3.2.6 on 2021-09-01 06:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_fonts_site_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonts',
            name='site_color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FF0000', max_length=18),
        ),
    ]
