# Generated by Django 3.2.6 on 2021-09-01 10:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_fonts_site_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonts',
            name='site_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
