# Generated by Django 3.2.6 on 2021-09-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_manageappointments_manageblog_managechangepassword_manageexperience_manageportfolio_manageservices_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageskills',
            name='skill_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manageskills',
            name='sub_skill_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
