# Generated by Django 3.2.6 on 2021-09-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20210922_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageskills',
            name='skill_status',
        ),
        migrations.RemoveField(
            model_name='manageskills',
            name='sub_skill_status',
        ),
    ]
