# Generated by Django 3.2.6 on 2021-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20210922_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageskills',
            name='sub_skill_status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
