# Generated by Django 3.2.6 on 2021-09-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_manageskills_sub_skill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageAddSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('skill_status', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManageAddSubSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_status', models.BooleanField(blank=True, default=True)),
                ('service_details', models.TextField(blank=True, null=True)),
                ('skills', models.CharField(choices=[], max_length=255, null=True)),
                ('sub_skill_name', models.CharField(max_length=255, null=True)),
                ('sub_skill_level', models.CharField(choices=[], max_length=255, null=True)),
                ('sub_order', models.IntegerField(blank=True, null=True)),
                ('sub_skill_status', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ManageSkills',
        ),
    ]
