# Generated by Django 3.2.6 on 2021-09-24 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20210924_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageaddsubskills',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.manageaddskills'),
        ),
    ]
