# Generated by Django 3.2.6 on 2021-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_manageaddsubskills_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageaddsubskills',
            name='sub_skill_level',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90', '90%'), ('100%', '100%')], max_length=255, null=True),
        ),
    ]
