# Generated by Django 3.2.6 on 2021-09-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_manageaddskills_skill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageaddskills',
            name='skill_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='manageaddsubskills',
            name='sub_skill_status',
            field=models.BooleanField(blank=True),
        ),
    ]
