# Generated by Django 3.2.6 on 2021-09-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20210928_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageaddskills',
            name='skill_status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
