# Generated by Django 3.2.6 on 2021-08-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('followers', models.FloatField(blank=True, max_length=255, null=True)),
                ('following', models.FloatField(blank=True, max_length=255, null=True)),
                ('portfolio', models.FloatField(blank=True, max_length=255, null=True)),
                ('views', models.FloatField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
