# Generated by Django 3.2.6 on 2021-08-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='google_Analytics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='linked_In',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
