# Generated by Django 3.2.6 on 2021-08-13 03:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210813_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linked_In', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('google_Analytics', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('about_me', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('followers', models.FloatField(blank=True, max_length=255, null=True)),
                ('following', models.FloatField(blank=True, max_length=255, null=True)),
                ('portfolio', models.FloatField(blank=True, max_length=255, null=True)),
                ('views', models.FloatField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
