# Generated by Django 3.2.6 on 2021-08-16 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210813_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsettings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.updateinfo'),
        ),
    ]
