# Generated by Django 3.2.6 on 2021-08-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_socialsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsettings',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.updateinfo'),
        ),
    ]
