# Generated by Django 3.2.6 on 2021-08-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_socialsettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinfo',
            name='agree',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
