# Generated by Django 3.2.6 on 2021-08-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210817_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateinfo',
            name='agree',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
