# Generated by Django 3.2.6 on 2021-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('follow_or_unfollow', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=True)),
                ('appointment', models.BooleanField(default=True)),
                ('blogs', models.BooleanField(default=True)),
                ('portfolio', models.BooleanField(default=True)),
                ('skill', models.BooleanField(default=True)),
                ('service', models.BooleanField(default=True)),
                ('experience', models.BooleanField(default=True)),
                ('testimonials', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('follow_or_unfollow', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=False)),
                ('appointment', models.BooleanField(default=True)),
                ('blogs', models.BooleanField(default=False)),
                ('portfolio', models.BooleanField(default=False)),
                ('skill', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('experience', models.BooleanField(default=False)),
                ('testimonials', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('follow_or_unfollow', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=True)),
                ('appointment', models.BooleanField(default=True)),
                ('blogs', models.BooleanField(default=False)),
                ('portfolio', models.BooleanField(default=False)),
                ('skill', models.BooleanField(default=True)),
                ('service', models.BooleanField(default=True)),
                ('experience', models.BooleanField(default=False)),
                ('testimonials', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('follow_or_unfollow', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=True)),
                ('appointment', models.BooleanField(default=True)),
                ('blogs', models.BooleanField(default=True)),
                ('portfolio', models.BooleanField(default=True)),
                ('skill', models.BooleanField(default=True)),
                ('service', models.BooleanField(default=True)),
                ('experience', models.BooleanField(default=True)),
                ('testimonials', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('follow_or_unfollow', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=False)),
                ('appointment', models.BooleanField(default=True)),
                ('blogs', models.BooleanField(default=False)),
                ('portfolio', models.BooleanField(default=False)),
                ('skill', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('experience', models.BooleanField(default=False)),
                ('testimonials', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('follow_or_unfollow', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=True)),
                ('appointment', models.BooleanField(default=True)),
                ('blogs', models.BooleanField(default=False)),
                ('portfolio', models.BooleanField(default=False)),
                ('skill', models.BooleanField(default=True)),
                ('service', models.BooleanField(default=True)),
                ('experience', models.BooleanField(default=False)),
                ('testimonials', models.BooleanField(default=True)),
            ],
        ),
    ]
