# Generated by Django 3.2.6 on 2021-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlypro',
            name='price',
            field=models.FloatField(default=10),
        ),
    ]
