# Generated by Django 3.2.6 on 2021-08-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_yearlypro_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlystudent',
            name='follow_or_unfollow',
            field=models.BooleanField(default=False),
        ),
    ]
