# Generated by Django 3.2.6 on 2021-08-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_monthlystudent_follow_or_unfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypro',
            name='price',
            field=models.FloatField(default=2),
        ),
    ]
